package com.mycompany.car_rental_system;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class car extends javax.swing.JFrame {

    Connection con;
    int lastind = 0;
    DefaultComboBoxModel model;

    //the value of each string in the array is matchable with the corrosponding feature as shown in the design
 
     String feature[] = {null, null, null,null,null, null};


     public void make_connector() {

        try {

            DriverManager.registerDriver(new org.postgresql.Driver());
            String info = "jdbc:postgresql://localhost:5432/postgres";
            con = DriverManager.getConnection(info, "ban", "ban123");

        } catch (Exception ex) {
            //since we have an error with data base so we must to exit our application 
            JOptionPane.showMessageDialog(null, "Error Happens With Your Data Base Connection!", "Data Base Error", JOptionPane.ERROR_MESSAGE + JOptionPane.OK_OPTION);
            System.exit(0);
        }

    }

    public void set_last_added_pk_for_idjtf() {

        make_connector();

        try {

            con.setAutoCommit(false);
            //fetch the pk column
            String q = "select MAX (veichleid) AS max_value from veichle";
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery(q);

            while (r.next() == true) {
                lastind = r.getInt("max_value");
            }
            lastind++;

            con.commit();
            con.close();
            con = null;

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error Happens With Your Data Base Connection!", "Data Base Error", JOptionPane.ERROR_MESSAGE + JOptionPane.OK_OPTION);
            System.exit(0);

        }

    }

    // Creates new form car
    public car() {
        initComponents();
        set_last_added_pk_for_idjtf();
        this.jtf_id.setText(String.valueOf(lastind));

        model = (DefaultComboBoxModel) this.brandboxcomp.getModel();
        //set up the brand item for the compo box 
        show_brands_on_brand_comp_box();

       
        set_action_commands_for_rbs();

        this.bg_geer.add(this.jrb_auto);
        this.bg_geer.add(this.jrb_manual);

        //purpose groub
        this.bg_purpose.add(this.jrb_sport);
        this.bg_purpose.add(this.jrb_lux);
        this.bg_purpose.add(this.jrb_eco);

     

        this.setLocationRelativeTo(null);
        this.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        this.setResizable(false);

    }

    public void set_action_commands_for_rbs() {

        this.jrb_auto.setActionCommand("Automatic");
        this.jrb_manual.setActionCommand("Manual");
        this.jrb_sport.setActionCommand("Sport");
        this.jrb_lux.setActionCommand("Luxury");
        this.jrb_eco.setActionCommand("Economic");
    
        this.jrb_air.setActionCommand("Air_Bags");
        this.jrb_bluetooth.setActionCommand("Bluetooth");
        this.jrb_heatedseat.setActionCommand("Heated_Seats");
        this.jrb_sunroof.setActionCommand("SunRoof");
        this.jrb_gps.setActionCommand("GPS");
        this.jrb_parkingcam.setActionCommand("Parking_Cameras");

        return;
    }

    public void show_brands_on_brand_comp_box() {

        make_connector();

        try {

            con.setAutoCommit(false);
            String q = "select brandname from veichletype";
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery(q);

            //to fetch the rows 
            while (r.next() == true) {

                model.addElement(r.getString("brandname"));

            }

            con.commit();
            con.close();
            con = null;

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error Happens With Your Data Base Connection!", "Data Base Error", JOptionPane.ERROR_MESSAGE + JOptionPane.OK_OPTION);
            System.exit(0);

        }

        return;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton2 = new javax.swing.JButton();
        bg_geer = new javax.swing.ButtonGroup();
        bg_purpose = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        brandboxcomp = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jtf_model = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jtf_color = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jrb_auto = new javax.swing.JRadioButton();
        jrb_manual = new javax.swing.JRadioButton();
        jLabel7 = new javax.swing.JLabel();
        jtf_price = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jrb_air = new javax.swing.JRadioButton();
        jrb_sunroof = new javax.swing.JRadioButton();
        jrb_bluetooth = new javax.swing.JRadioButton();
        jrb_gps = new javax.swing.JRadioButton();
        jrb_heatedseat = new javax.swing.JRadioButton();
        jrb_parkingcam = new javax.swing.JRadioButton();
        jPanel4 = new javax.swing.JPanel();
        addcarbtn = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jtf_id = new javax.swing.JTextField();
        jrb_sport = new javax.swing.JRadioButton();
        jrb_lux = new javax.swing.JRadioButton();
        jrb_eco = new javax.swing.JRadioButton();

        jButton2.setBackground(new java.awt.Color(82, 140, 197));
        jButton2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Add");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 153));

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cars");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(82, 140, 197));
        jLabel2.setText("ID");
        jLabel2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(82, 140, 197));
        jLabel3.setText("Brand");
        jLabel3.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        brandboxcomp.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        brandboxcomp.setForeground(new java.awt.Color(137, 123, 203));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(82, 140, 197));
        jLabel4.setText("Model");
        jLabel4.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jtf_model.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtf_model.setForeground(new java.awt.Color(137, 123, 203));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(82, 140, 197));
        jLabel5.setText("Color");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jtf_color.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtf_color.setForeground(new java.awt.Color(137, 123, 203));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(82, 140, 197));
        jLabel6.setText("GearBox");
        jLabel6.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jrb_auto.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_auto.setForeground(new java.awt.Color(82, 140, 197));
        jrb_auto.setText("Automatic");

        jrb_manual.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_manual.setForeground(new java.awt.Color(82, 140, 197));
        jrb_manual.setText("Manual");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 27)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Features");
        jLabel7.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jtf_price.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtf_price.setForeground(new java.awt.Color(137, 123, 203));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(82, 140, 197));
        jLabel8.setText("Purpose");
        jLabel8.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jrb_air.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_air.setForeground(new java.awt.Color(82, 140, 197));
        jrb_air.setText("Air Bags");

        jrb_sunroof.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_sunroof.setForeground(new java.awt.Color(82, 140, 197));
        jrb_sunroof.setText("SunRoof");

        jrb_bluetooth.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_bluetooth.setForeground(new java.awt.Color(82, 140, 197));
        jrb_bluetooth.setText("Bluetooth");

        jrb_gps.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_gps.setForeground(new java.awt.Color(82, 140, 197));
        jrb_gps.setText("GPS");

        jrb_heatedseat.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_heatedseat.setForeground(new java.awt.Color(82, 140, 197));
        jrb_heatedseat.setText("Heated Seats");

        jrb_parkingcam.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_parkingcam.setForeground(new java.awt.Color(82, 140, 197));
        jrb_parkingcam.setText("Parking Cameras");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_air, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_sunroof, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(80, 80, 80)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_bluetooth, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_gps, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(97, 97, 97)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jrb_parkingcam, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jrb_heatedseat, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(277, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_air)
                    .addComponent(jrb_bluetooth)
                    .addComponent(jrb_heatedseat))
                .addGap(43, 43, 43)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrb_sunroof)
                    .addComponent(jrb_gps)
                    .addComponent(jrb_parkingcam))
                .addContainerGap(66, Short.MAX_VALUE))
        );

        addcarbtn.setBackground(new java.awt.Color(82, 140, 197));
        addcarbtn.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        addcarbtn.setForeground(new java.awt.Color(255, 255, 255));
        addcarbtn.setText("Add Car");
        addcarbtn.setFocusable(false);
        addcarbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addcarbtnActionPerformed(evt);
            }
        });

        jButton7.setBackground(new java.awt.Color(82, 140, 197));
        jButton7.setFont(new java.awt.Font("Segoe UI", 1, 23)); // NOI18N
        jButton7.setForeground(new java.awt.Color(255, 255, 255));
        jButton7.setText("Cars List");
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, 226, Short.MAX_VALUE)
            .addComponent(addcarbtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addcarbtn)
                .addGap(34, 34, 34)
                .addComponent(jButton7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 25)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(82, 140, 197));
        jLabel9.setText("Price Per Day");
        jLabel9.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jtf_id.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jtf_id.setForeground(new java.awt.Color(137, 123, 203));
        jtf_id.setEnabled(false);

        jrb_sport.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_sport.setForeground(new java.awt.Color(82, 140, 197));
        jrb_sport.setText("Sport");

        jrb_lux.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_lux.setForeground(new java.awt.Color(82, 140, 197));
        jrb_lux.setText("Luxury");

        jrb_eco.setFont(new java.awt.Font("Segoe UI", 1, 15)); // NOI18N
        jrb_eco.setForeground(new java.awt.Color(82, 140, 197));
        jrb_eco.setText("Economic");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(18, 18, 18)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(brandboxcomp, 0, 177, Short.MAX_VALUE)
                                        .addComponent(jtf_id)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtf_color))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jtf_model, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(112, 112, 112)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_sport, javax.swing.GroupLayout.DEFAULT_SIZE, 73, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jrb_lux, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb_eco, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jrb_manual, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jrb_auto, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jtf_price, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(25, 25, 25)))
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 89, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(jtf_id, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jtf_price, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(brandboxcomp, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel6)
                                .addComponent(jrb_manual)
                                .addComponent(jrb_auto)))
                        .addGap(22, 22, 22)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel4)
                            .addComponent(jtf_model, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(jrb_sport)
                        .addComponent(jrb_lux)
                        .addComponent(jrb_eco)))
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jtf_color, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(61, 61, 61)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // move to cars list page
        new carlist().setVisible(true);
    }//GEN-LAST:event_jButton7ActionPerformed

    private void addcarbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addcarbtnActionPerformed
     

        String brandname1 = String.valueOf(this.brandboxcomp.getSelectedItem());
        String model = this.jtf_model.getText();
        String color = this.jtf_color.getText();
        String price = this.jtf_price.getText();

        //we need to get up the brand id ( fk )
        int brandid = get_brand_id(brandname1);
 
        //fill out the chosen features which are found in this car 
        fill_features();

        //we need to check if we have selection or mot for the radio buttons 
        if (verify_selection() == true) {
            JOptionPane.showMessageDialog(null, "Invalid Input Values !", "Nulls Errors ", JOptionPane.OK_OPTION + JOptionPane.ERROR_MESSAGE);
            this.reinitialize_the_feilds();

            return;
        }

        String purpose = this.bg_purpose.getSelection().getActionCommand();
      
        String gearbox = this.bg_geer.getSelection().getActionCommand();
        int price1 = Integer.parseInt(price);

        //we need to verify the input strings 
        String temp[] = {model, color, price};

        for (int c = 0; c < 3; c++) {
            boolean flag = verify_strings(temp[c]);
            if (flag == true) {
                JOptionPane.showMessageDialog(null, "Invalid Input Values !", "Spaces Errors ", JOptionPane.OK_OPTION + JOptionPane.ERROR_MESSAGE);
                this.reinitialize_the_feilds();
                return;
            }

        }

       
        make_connector();

        try {

            
             String arr="ARRAY['" + String.join("','", feature) + "']";
            
            con.setAutoCommit(false);

            String q = "insert into veichle  values('" + lastind + "','" + color + "','" + price1 + "','" + model + "', '" + gearbox + "','" + 1 + "','" + brandid + "','" + purpose + "',"+arr+")";
            Statement s = con.createStatement();
            s.executeUpdate(q);
           
           
             lastind++;
            this.jtf_id.setText(String.valueOf(lastind));

            con.commit();
            con.close();
            con = null;

            JOptionPane.showMessageDialog(null, "New Veichle(Car) Has Been Successfully Added To Your Comapny !", "Car Added", JOptionPane.OK_OPTION + JOptionPane.PLAIN_MESSAGE);
            reinitialize_the_feilds();

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Data Base Error", JOptionPane.ERROR_MESSAGE + JOptionPane.OK_OPTION);
            System.exit(0);

        }


    }//GEN-LAST:event_addcarbtnActionPerformed

    public void fill_features() {

        if (this.jrb_air.isSelected() == true) {
            feature[0] = this.jrb_air.getActionCommand();
        }

        if (this.jrb_bluetooth.isSelected() == true) {
            feature[1] = this.jrb_bluetooth.getActionCommand();
        }

        if (this.jrb_heatedseat.isSelected() == true) {
            feature[2] = this.jrb_heatedseat.getActionCommand();
        }

        if (this.jrb_sunroof.isSelected() == true) {
            feature[3] = this.jrb_sunroof.getActionCommand();
        }

        if (this.jrb_gps.isSelected() == true) {
            feature[4] = this.jrb_gps.getActionCommand();
        }

        if (this.jrb_parkingcam.isSelected() == true) {
            feature[5] = this.jrb_parkingcam.getActionCommand();
        }

        return;
    }

    public boolean verify_selection() {

        if ((this.bg_geer.getSelection() == null) || (this.bg_purpose.getSelection() == null)   ) {
            return true; //not selected buttons 
        }
        return false;//selected ones

    }

    public void reinitialize_the_feilds() {

        this.jtf_color.setText(null);
        this.jtf_model.setText(null);
        this.jtf_price.setText(null);
        this.bg_geer.clearSelection();
        this.bg_purpose.clearSelection();
      
        this.jrb_air.setSelected(false);
        this.jrb_bluetooth.setSelected(false);
        this.jrb_heatedseat.setSelected(false);
        this.jrb_sunroof.setSelected(false);
        this.jrb_gps.setSelected(false);
        this.jrb_parkingcam.setSelected(false);

        return;
    }

    public boolean verify_strings(String x) {

        if ((x.contains(" ") == true) || (x.isEmpty() == true)) {
            return true;//has spaces
        }
        return false;// not has spaces

    }

    public int get_brand_id(String brandname2) {

        make_connector();
        int ind = 0;

        try {

            con.setAutoCommit(false);

            String q = "select veichletypeid from veichletype where brandname='" + brandname2 + "'";
            Statement s = con.createStatement();
            ResultSet r = s.executeQuery(q);

            r.next();
            ind = r.getInt("veichletypeid");

            con.commit();
            con.close();
            con = null;

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "Error Happens With Your Data Base Connection!", "Data Base Error", JOptionPane.ERROR_MESSAGE + JOptionPane.OK_OPTION);
            System.exit(0);

        }

        return ind;

    }

    //@param args the command line arguments
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(car.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new car().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addcarbtn;
    private javax.swing.ButtonGroup bg_geer;
    private javax.swing.ButtonGroup bg_purpose;
    private javax.swing.JComboBox<String> brandboxcomp;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton7;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JRadioButton jrb_air;
    private javax.swing.JRadioButton jrb_auto;
    private javax.swing.JRadioButton jrb_bluetooth;
    private javax.swing.JRadioButton jrb_eco;
    private javax.swing.JRadioButton jrb_gps;
    private javax.swing.JRadioButton jrb_heatedseat;
    private javax.swing.JRadioButton jrb_lux;
    private javax.swing.JRadioButton jrb_manual;
    private javax.swing.JRadioButton jrb_parkingcam;
    private javax.swing.JRadioButton jrb_sport;
    private javax.swing.JRadioButton jrb_sunroof;
    private javax.swing.JTextField jtf_color;
    private javax.swing.JTextField jtf_id;
    private javax.swing.JTextField jtf_model;
    private javax.swing.JTextField jtf_price;
    // End of variables declaration//GEN-END:variables

}
